// Extra real-browser cases composed into the existing nav/calculator regression runner.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async ({page,s,check,reset,fill,snapshot,capture,OUTPUT})=>{
 const key='dim-glacier-planner-state-v1';
 const stamp=()=>page.evaluate(()=>priceLastModified);
 const persist=()=>page.waitForTimeout(200);
 const metadata=()=>page.locator('#price_last_modified').textContent();
 const run=(name,fn)=>check(s.id+'-price-metadata-'+name,fn,page);
 await run('fresh-reset-default-date',async()=>{await reset(page,s);assert.equal(await stamp(),null);assert.equal(await metadata(),'—');assert.equal(await page.locator('#default_price_date').textContent(),'12 เม.ย. 2569');await persist();assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).metadata||null,key),null);s.priceDefaults=await snapshot(page);});
 await run('all-labels-and-click-focus',async()=>{
  const result=await page.evaluate(()=>{const all=[...document.querySelectorAll('[id]')].map(e=>e.id);const fields=[...document.querySelectorAll('input[type=text],input[type=number]')].map(e=>({id:e.id,labels:[...e.labels].map(l=>({for:l.htmlFor,text:l.textContent.trim()})),inputmode:e.inputMode,type:e.type}));return{duplicates:all.filter((id,i)=>all.indexOf(id)!==i),dangling:[...document.querySelectorAll('label[for]')].filter(l=>!l.control).map(l=>l.htmlFor),fields};});
  assert.deepEqual(result.duplicates,[]);assert.deepEqual(result.dangling,[]);assert.equal(result.fields.length,21);
  for(const field of result.fields){assert.equal(field.labels.length,1,field.id);assert(field.labels[0].text);await page.locator(`label[for="${field.id}"]`).click();assert.equal(await page.evaluate(()=>document.activeElement.id),field.id);if(field.type==='text')assert(['numeric','decimal'].includes(field.inputmode));}s.priceLabels=result;
 });
 await run('edit-price-comma-total-persist',async()=>{await reset(page,s);const before=await snapshot(page);await fill(page,{p_petal:12345});assert.equal(await page.locator('#p_petal').inputValue(),'12,345');assert.notDeepEqual((await snapshot(page)).costs,before.costs);assert(await stamp());await persist();const stored=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);assert.equal(stored.values.p_petal,'12,345');assert.equal(stored.metadata.priceLastModified,await stamp());assert.notEqual(await metadata(),'—');await capture(page,s.id+'-price-metadata-edited');});
 await run('rate-edit-and-local-thai-format',async()=>{const before=await stamp();await page.waitForTimeout(10);await fill(page,{rate_thb:9.25});assert.notEqual(await stamp(),before);const expected=await page.evaluate(()=>{const d=new Date(priceLastModified),p=new Intl.DateTimeFormat('th-TH-u-ca-buddhist-nu-latn',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d),v=t=>p.find(x=>x.type===t).value;return`${v('day')} ${v('month')} ${v('year')} ${v('hour')}:${v('minute')}`;});assert.equal(await metadata(),expected);});
 await run('non-price-and-noop-events-do-not-stamp',async()=>{const before=await stamp();await page.locator('#sel_s4_method').selectOption('coupon');await fill(page,{sel_cur_stage:2,sel_target_stage:6,qty_cube:3,qty_device:2,manual_cost:234567});await page.locator('[data-view="raw"]').click();await page.locator('#p_petal').fill('12345');await page.locator('#p_petal').press('Tab');assert.equal(await stamp(),before);});
 await run('reload-preserves-price-and-time',async()=>{await persist();const before=await snapshot(page),time=await stamp();await page.reload({waitUntil:'networkidle'});assert.equal(await stamp(),time);const after=await snapshot(page);assert.deepEqual(after.inputs,before.inputs);assert.deepEqual(after.costs,before.costs);});
 await run('old-state-and-invalid-metadata',async()=>{for(const bad of [undefined,'invalid','2026-02-30T00:00:00.000Z',23]){await page.evaluate(({key,bad})=>{const p=buildExportPayload();p.values.p_petal='54,321';if(bad!==undefined)p.metadata={priceLastModified:bad};localStorage.setItem(key,JSON.stringify(p));},{key,bad});await page.reload({waitUntil:'networkidle'});assert.equal(await stamp(),null);assert.equal(await metadata(),'—');assert.equal(await page.locator('#p_petal').inputValue(),'54,321');}});
 await run('reset-restores-default-values-and-clears-time',async()=>{await fill(page,{p_petal:99999,rate_thb:88});await reset(page,s);await persist();assert.equal(await stamp(),null);assert.equal(await metadata(),'—');assert.deepEqual(await snapshot(page),s.priceDefaults);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).metadata||null,key),null);});
 for(const format of ['json','csv','xlsx'])await run(format+'-old-file-import-stamps-after-success',async()=>{await reset(page,s);const before=Date.now();const file=path.join(OUTPUT,s.formats[format].file);await page.locator('#file_import').setInputFiles(file);await page.waitForFunction(()=>priceLastModified!==null);assert(new Date(await stamp()).getTime()>=before);assert.deepEqual(await snapshot(page),s.formats[format].imported);const first=await stamp();await page.waitForTimeout(10);await page.locator('#file_import').setInputFiles(file);await page.waitForFunction(t=>priceLastModified!==t,first);await persist();assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).metadata.priceLastModified,key),await stamp());});
 await run('import-ignores-file-timestamp-and-rejected-partial-import-does-not-stamp',async()=>{const file=path.join(OUTPUT,s.id+'-price-metadata-oldstamp.json');const payload=await page.evaluate(()=>buildExportPayload());payload.values.p_petal='65432';payload.fields.find(f=>f.id==='p_petal').value='65432';payload.metadata={priceLastModified:'2000-01-01T00:00:00.000Z'};fs.writeFileSync(file,JSON.stringify(payload));const before=Date.now();await page.locator('#file_import').setInputFiles(file);await page.waitForFunction(()=>document.getElementById('p_petal').value==='65,432');assert(new Date(await stamp()).getTime()>=before);const old=await stamp(),state=await snapshot(page);fs.writeFileSync(file,JSON.stringify({values:{qty_cube:4}}));page.once('dialog',d=>d.dismiss());await page.locator('#file_import').setInputFiles(file);await page.waitForTimeout(100);assert.equal(await stamp(),old);assert.deepEqual(await snapshot(page),state);});
 await run('failed-import-does-not-stamp',async()=>{const before=await stamp(),values=await snapshot(page),file=path.join(OUTPUT,s.id+'-price-metadata-invalid.json');fs.writeFileSync(file,JSON.stringify({values:{p_petal:-1}}));page.once('dialog',d=>d.dismiss());await page.locator('#file_import').setInputFiles(file);await page.waitForTimeout(100);assert.equal(await stamp(),before);assert.deepEqual(await snapshot(page),values);});
 await run('portable-json-no-metadata',async()=>{const pending=page.waitForEvent('download');await page.locator('#btn_export_json').click();const d=await pending,file=path.join(OUTPUT,s.id+'-metadata-export.json');await d.saveAs(file);const payload=JSON.parse(fs.readFileSync(file));assert.deepEqual(Object.keys(payload).sort(),['app','exportedAt','fields','values','version']);assert(!('metadata' in payload));});
 await run('mobile-metadata-geometry',async()=>{await page.locator('#default_price_date').scrollIntoViewIfNeeded();const g=await page.evaluate(()=>{const e=document.getElementById('price_last_modified'),r=e.getBoundingClientRect(),card=document.getElementById('card_market').getBoundingClientRect();return{width:innerWidth,left:r.left,right:r.right,cardRight:card.right,documentWidth:document.documentElement.scrollWidth};});assert(g.left>=0);assert(g.right<=g.cardRight+1);assert(g.documentWidth<=s.geometry.documentWidth+1);await capture(page,s.id+'-price-metadata-final');});
};
