const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const html=require('../qa/nav140/normalize.cjs')(require('../qa/ui-cohesion/normalize.cjs')(fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8')));
const baseline=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../qa/price-metadata/baseline.json')));
const helper=html.slice(html.indexOf('    // Price metadata is local-only'),html.indexOf('    function setStorageStatus'));
const fieldDefs=html.match(/const FIELD_DEFS = (\[[\s\S]*?\n    \]);/)[1];
function fixture(){const inputs=Object.fromEntries(baseline.inputs.filter(x=>/id="/.test(x)).map(x=>[x.match(/id="([^"]+)"/)[1],{id:x.match(/id="([^"]+)"/)[1],value:x.match(/value="([^"]*)"/)?.[1]||'',addEventListener(){}}]));for(const id of ['sel_cur_stage','sel_target_stage','sel_s4_method','sel_s3_method'])inputs[id]={id,value:'0'};inputs.price_last_modified={textContent:''};const ctx={document:{getElementById:id=>inputs[id],addEventListener(){}},Intl,Date,isApplyingState:false,saves:0,parse:x=>Number(String(x).replace(/,/g,''))||0};ctx.scheduleSave=()=>ctx.saves++;vm.createContext(ctx);vm.runInContext(`const FIELD_DEFS=${fieldDefs};\n${helper}\nbindPriceMetadata();`,ctx);return{ctx,inputs,run:s=>vm.runInContext(s,ctx)};}
test('only exact reviewed metadata/labels edits; old default inputs, styles, business logic and nav reconstruct unchanged',()=>{const original=require('./price-metadata-normalize.cjs')(require('../qa/first-run/normalize.cjs')(html));assert.equal(crypto.createHash('sha256').update(original).digest('hex'),baseline.indexSha256);assert.deepEqual([...require('../qa/first-run/normalize.cjs')(html).matchAll(/<input\b[^>]*>/g)].map(m=>m[0]),baseline.inputs);});
test('all 21 numeric fields have explicit labels; labels and IDs are valid and unique',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);const fors=[...html.matchAll(/<label\b[^>]*\bfor="([^"]+)"/g)].map(m=>m[1]);for(const id of fors)assert(ids.includes(id),id);for(const input of baseline.inputs.filter(x=>/type="(?:number|text)"/.test(x))){const id=input.match(/id="([^"]+)"/)[1];assert.equal(fors.filter(x=>x===id).length,1,id);}assert.equal(baseline.inputs.filter(x=>/type="(?:number|text)"/.test(x)).length,21);});
test('fresh metadata blank; all 18 price fields stamp on effective edits, including rate',()=>{const f=fixture();assert.equal(f.inputs.price_last_modified.textContent,'—');const ids=f.run('PRICE_FIELD_IDS');assert.equal(ids.length,18);for(const id of ids){f.inputs[id].value='998877';f.run(`trackPriceEdit({target:document.getElementById('${id}')})`);assert(f.run('validPriceTimestamp(priceLastModified)'));}assert.equal(f.ctx.saves,18);});
test('non-price fields, unchanged values, commas and composing input do not stamp',()=>{const f=fixture();for(const id of ['qty_cube','qty_device','manual_cost','sel_cur_stage','sel_target_stage','sel_s4_method','sel_s3_method']){f.inputs[id].value='123';f.run(`trackPriceEdit({target:document.getElementById('${id}')})`);}f.inputs.p_petal.value='10400';f.run("trackPriceEdit({target:document.getElementById('p_petal')})");f.inputs.p_petal._isComposing=true;f.inputs.p_petal.value='12345';f.run("trackPriceEdit({target:document.getElementById('p_petal')})");assert.equal(f.run('priceLastModified'),null);assert.equal(f.ctx.saves,0);f.inputs.p_petal._isComposing=false;f.run("trackPriceEdit({target:document.getElementById('p_petal')})");assert.equal(f.ctx.saves,1);});
test('invalid, missing or noncanonical stored timestamps gracefully display a dash',()=>{const f=fixture();for(const value of [null,undefined,17,{},'bad','2026-02-30T00:00:00.000Z','99999-01-01T00:00:00.000Z']){f.ctx.value=value;assert.equal(f.run('formatPriceTimestamp(value)'),'—');}assert.equal(f.run("validPriceTimestamp('2026-10-02T11:12:00.000Z')"),'2026-10-02T11:12:00.000Z');});
test('date formatting has Thai Buddhist year and a graceful Intl fallback using local components',()=>{const f=fixture();const iso='2026-10-02T11:12:00.000Z';assert.match(f.run(`formatPriceTimestamp('${iso}')`),/2569/);f.ctx.Intl={DateTimeFormat(){throw Error('Unavailable')}};const d=new Date(iso);assert.equal(f.run(`formatPriceTimestamp('${iso}')`),`${d.getDate()} ต.ค. 2569 ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`);});
test('all original export functions, parser, formulas and default prices remain exact bytes',()=>{const original=require('./price-metadata-normalize.cjs')(require('../qa/first-run/normalize.cjs')(html));for(const [start,end] of [['function buildExportPayload()','function applyStateValues'],['function exportJson()','async function importFile'],['function sanitizeNumberTyping','// Init']]){const get=s=>s.slice(s.indexOf(start),s.indexOf(end));assert.equal(get(require('../qa/first-run/normalize.cjs')(html)),get(original));}for(const script of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);});
